### ISSUE TITLE
use moudle.rule('vue') when cdn use

### ISSUE THREAD

**Issue by callmesoul** [neutrinojs/webpack-chain#306]
I user cdn  to import vue:
`
config.externals = {
      vue: {
        root: 'Vue',
        commonjs: 'vue',
        commonjs2: 'vue',
        amd: 'vue'
      },
      'element-ui': 'ELEMENT'
    }

    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(options => {
        options.compilerOptions.directives = {
          html (node, directiveMeta) {
            (node.props || (node.props = [])).push({
              name: 'innerHTML',
              // value: `xss(_s(${directiveMeta.value}),${JSON.stringify(xssOp)})`
              value: `xss(_s(${directiveMeta.value}))`
            })
          }
        }
        return options
      })
`

but `config.module .rule('vue')` will build vue not in cdn.
when I 'yarn remove vue' :
···
 ERROR  TypeError: Cannot read property 'compilerOptions' of undefined
TypeError: Cannot read property 'compilerOptions' of undefined
    at D:\vue.config.js:34:17
    at Object.tap (D:\node_modules\webpack-chain\src\Use.js:14:20)
    at chainWebpack (D:\vue.config.js:33:8)
    at D:\node_modules\@vue\cli-service\lib\Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\node_modules\@vue\cli-service\lib\Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (D:\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at serve (D:\node_modules\@vue\cli-service\lib\commands\serve.js:75:31)
    at Service.run (D:\node_modules\@vue\cli-service\lib\Service.js:230:12)
    at Object.<anonymous> (D:\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
error Command failed with exit code 1.
···

how can i use `.rule('vue')` to import cdn vue

**Comment by edmorley** [comment]
Hi! Please ask the Vue project for support. This project is used by Vue, but the config you're adjusting was set by Vue.

Thanks!
